// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Service-role key — bypassa RLS. Auth é feita pelo portal central (vpsistema.com).
const SUPABASE_URL = 'https://jbwgjegelhoueygcvafq.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impid2dqZWdlbGhvdWV5Z2N2YWZxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDY1NjE0MiwiZXhwIjoyMDkwMjMyMTQyfQ.KHcFzjQ8yTqIHs38wgAO_E5HpwZKdyjhairK0wXMWrM';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    autoRefreshToken: false,
    persistSession: false,
  },
});
